# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ece.cmu.edu/usr/sjurcsek/Private/18545/final/gen_final/gen_final.srcs/sources_1/ip/DMA_RAM_M68/DMA_RAM_M68.xci
# IP: The module: 'DMA_RAM_M68' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/sjurcsek/Private/18545/final/gen_final/gen_final.srcs/sources_1/ip/DMA_RAM_M68/DMA_RAM_M68_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_RAM_M68'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /afs/ece.cmu.edu/usr/sjurcsek/Private/18545/final/gen_final/gen_final.srcs/sources_1/ip/DMA_RAM_M68/DMA_RAM_M68.xci
# IP: The module: 'DMA_RAM_M68' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/sjurcsek/Private/18545/final/gen_final/gen_final.srcs/sources_1/ip/DMA_RAM_M68/DMA_RAM_M68_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_RAM_M68'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
